# Generated by Django 4.1 on 2024-07-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
